# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.User', unique=True)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
