# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180224_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='score',
            field=models.FloatField(),
        ),
    ]
